build:
  stage: build
  cache:
    key: coursier-cache-key
    paths:
      - ${COURSIER_CACHE}
  script:
    - SBT_POD=$(kubectl get po -n sbt -l "app.kubernetes.io/instance=sbt" -o=name)
    - |
      kubectl exec -i -n sbt "${SBT_POD}" -- bash <<EOF
        export COURSIER_CACHE="${COURSIER_CACHE}"
        cd "${CI_PROJECT_DIR}"
        sbt compile test:compile test cq
      EOF

stages:
  - build
