name: Build

on: [push, pull_request]

defaults:
  run:
    shell: nix develop -v -c bash {0}

jobs:
  build:
    name: Build
    runs-on: [self-hosted, nix, chopsticks]
    env:
      PROTOC_CACHE: ${{ env.XDG_CACHE_HOME }}/protoc_cache
      COURSIER_CACHE: ${{ env.XDG_CACHE_HOME }}/coursier
      SBT_OPTS: "-Dsbt.global.base=${{ env.XDG_CACHE_HOME }}/sbt -Dsbt.ivy.home=${{ env.XDG_CACHE_HOME }}/ivy -Xmx4g -Xss6m"
    steps:
      - uses: actions/checkout@v2

      - name: Check code quality
        run: |
          sbt --client 'set ThisBuild / scalacOptions ++= Seq("-Werror")'
          sbt --client cq

      - name: Compile
        run: sbt --client compile

      - name: Compile tests
        run: sbt --client 'Test / compile'

      - name: Test
        run: sbt --client test
