name: Build

on: [push, pull_request]

defaults:
  run:
    shell: nix develop -v -c bash {0}

jobs:
  build:
    name: Build
    runs-on: [self-hosted, nix, chopsticks]
    steps:
      - uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          echo "PROTOC_CACHE=${XDG_CACHE_HOME}/protoc_cache" >> "${GITHUB_ENV}"
          echo "COURSIER_CACHE=${XDG_CACHE_HOME}/coursier" >> "${GITHUB_ENV}"
          echo "SBT_OPTS=-Dsbt.global.base=${XDG_CACHE_HOME}/sbt -Dsbt.ivy.home=${XDG_CACHE_HOME}/ivy -Xmx4g -Xss6m -XshowSettings:system" >> "${GITHUB_ENV}"

      - name: Check code quality
        run: |
          sbt --client 'set ThisBuild / scalacOptions ++= Seq("-Werror")'
          sbt --client cq

      - name: Compile
        run: sbt --client compile

      - name: Compile tests
        run: sbt --client 'Test / compile'

      - name: Debug
        run: |
          trap : TERM INT; sleep infinity & wait

      - name: Test
        run: sbt --client test
