name: Build and publish
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    container:
      image: shopstic/jdk11-sbt:1.3.12
    steps:
      - uses: actions/checkout@v2
      - name: Install FDB
        run: |
          apt-get update && \
            apt-get -qq -y install wget &&
            apt-get -qq -y install python2.7  &&
            apt-get -qq -y install python &&
            wget --no-check-certificate https://www.foundationdb.org/downloads/6.2.22/ubuntu/installers/foundationdb-clients_6.2.22-1_amd64.deb &&
            wget --no-check-certificate https://www.foundationdb.org/downloads/6.2.22/ubuntu/installers/foundationdb-server_6.2.22-1_amd64.deb &&
            dpkg -i foundationdb-clients_6.2.22-1_amd64.deb foundationdb-server_6.2.22-1_amd64.deb && \
            mkdir -p ~/.fdb && \
            cp /etc/foundationdb/fdb.cluster ~/.fdb/cluster.file
      - name: Build
        env:
          FATAL_WARNINGS: "true"
        run: sbt clean compile test:compile cq test bintray:publish bintrayRelease
